---
trust-domain: xpi

task-priority: lowest

taskgraph:
    register: xpi_taskgraph:register
    repositories:
        xpi:
            name: "XPI source"
            project-regex: '(?!xpi-template)'
        template:
            name: "XPI template"
            project-regex: 'xpi-template'
            # XXX
            #default-repository: https://github.com/mozilla-extensions/xpi-template
            #default-ref: master
            default-repository: https://github.com/escapewindow/xpi-template
            default-ref: shared-tc-dir
            type: git

workers:
    aliases:
        b-linux:
            provisioner: xpi-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux'
