---
trust-domain: xpi

task-priority: lowest

taskgraph:
    register: xpi_taskgraph:register
    decision-parameters: 'xpi_taskgraph.parameters:get_decision_parameters'
    repositories:
        xpi:
            name: "XPI source"
            project-regex: '(?!xpi-template)'
        template:
            name: "XPI template"
            project-regex: 'xpi-template'
            default-repository: https://github.com/mozilla-extensions/xpi-template
            default-ref: master
            type: git

workers:
    aliases:
        b-linux:
            provisioner: xpi-{level}
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux'
        dep-signing:
            provisioner: scriptworker-k8s
            implementation: scriptworker-signing
            os: scriptworker
            worker-type: xpi-t-signing

scriptworker:
    scope-prefix: project:xpi:releng
